### ISSUE TITLE
fly-esperanto not found

### ISSUE THREAD

**Issue by bjornstar** [bucaran/ember-app-demo#2]
$ npm install
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "/home/bjorn/.nvm/versions/node/v0.12.3/bin/node" "/home/bjorn/.nvm/versions/node/v0.12.3/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/fly-esperanto
npm ERR! 404 
npm ERR! 404 'fly-esperanto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ember-app-demo'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bjorn/ember-app-demo/npm-debug.log

**Comment by bucaran** [comment]
It's [up](https://www.npmjs.com/package/fly-esperanto). 
Released it as 0.1.0 as it's not a complete implementation of all of Esperanto's options. 

Will bump the major as soon as I get that done.
